Update kafka-client-go to latest version and bump app version to v.1.0.0
Financial-Times/pac-annotations-mapper pull request #10
Opened 2019-09-03 10:24 UTC by karsov

2019-09-03 14:00 UTC, MiroslavGatsanoga requested changes

2019-09-03 14:00 UTC, MiroslavGatsanoga commented on .circleci/config.yml
> +            go test -race -v -cover -coverprofile=${CIRCLE_COVERAGE_REPORT}/coverage.out ./... | go-junit-report > ${CIRCLE_TEST_REPORTS}/junit.xml
It is good to pass `-mod=readonly` here as well.

2019-09-03 15:42 UTC, MiroslavGatsanoga submitted a review, later dismissed

2019-09-04 10:21 UTC, gotha submitted a review, later dismissed

2019-09-04 11:48 UTC, MiroslavGatsanoga approved these changes

2019-09-04 11:53 UTC, gotha approved these changes

2019-09-05 07:23 UTC, merged